language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

os:
  - linux
  - windows

install:
  - pip install coveralls

script:
  - nosetests --with-coverage --cover-package=mathparse

after_success:
  - coveralls

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
      branch: deploy
