#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# mathparse documentation build configuration file, created by
# sphinx-quickstart on Tue Aug  8 07:11:36 2017.


# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

import os
import sys
from pathlib import Path
from datetime import datetime

current_directory = os.path.abspath('.')
parent_directory = os.path.abspath(os.path.join(current_directory, os.pardir))

sys.path.insert(0, parent_directory)

sys.path.append(str(Path('_ext').resolve()))

from mathparse import __version__ as mathparse_version

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'github',
    'canonical',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
source_suffix = ['.rst', '.md']

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'mathparse'
author = 'Gunther Cox'
copyright = '{}, {}'.format(
    datetime.now().year,
    author
)

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# The full version, including alpha/beta/rc tags
release = mathparse_version

# The short X.Y version
version = mathparse_version.rsplit('.', 1)[0]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = 'classic'

html_logo = '_static/mathparse.png'

html_favicon = '_static/favicon.ico'

# Theme options are theme-specific and customize the look and feel of a theme
# further. For a list of options available for each theme, see the
# documentation:
# https://www.sphinx-doc.org/en/master/usage/theming.html
html_theme_options = {
    'externalrefs': True,
    'sidebarbgcolor': '#300a24',
    'relbarbgcolor': '#26001b',
    'footerbgcolor': '#13000d',
    'headbgcolor': '#503949',
    'headtextcolor': '#e8ffca',
    'headlinkcolor': '#e8ffca',
    'sidebarwidth': '300px',
    # 'collapsiblesidebar': True,
}

html_show_sourcelink = True

html_baseurl = 'https://mathparse.chatterbot.us/'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = [
    'style.css'
]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.

# This is required for the alabaster theme
html_sidebars = {
    '**': ['searchbox.html', 'globaltoc.html']
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'mathparsedoc'

html_context = {
    'extra_css_files': [
        '_static/style.css'
    ]
}

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'mathparse.tex', 'mathparse Documentation',
     'Gunther Cox', 'manual'),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'mathparse', 'mathparse Documentation',
     [author], 1)
]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'mathparse', 'mathparse Documentation',
     author, 'mathparse', 'One line description of project.',
     'Miscellaneous'),
]


# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None)
}
